### ISSUE TITLE
Can't find a web-client-desktop/3.26.6

### ISSUE THREAD

**Issue by lonewookieman** [plexinc/plex-media-player#641]
I am attempting to install the Plex Media Player on Ubuntu 16.04, following the directions I get as far as "Building plex-media-player" in the documentation and when I try running the command "conan install .." I get an error:

web-client-desktop/3.26.2-3d9c616@plex/public: WARN: Can't find a 'web-client-desktop/3.26.2-3d9c616@plex/public' package for the specified options and settings:
- Settings: 
- Options: 

ERROR: Missing prebuilt package for 'web-client-desktop/3.26.2-3d9c616@plex/public'
Try to build it from sources with "--build web-client-desktop"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

Any suggestions on how to resolve this?  Thanks.

**Comment by stashhole** [comment]
I am experiencing the exact same error trying to build web-client from source fails as well as the repository at 'github.com/plexinc/plex-web-client' doesn't seem to exist or is a private repository. Any word on this?

**Comment by father-mande** [comment]
Hi,

Same
seem that plex conan server is out : 
conan remote list
conan.io: https://server.conan.io [Verify SSL: True]
plex: https://conan.plex.tv [Verify SSL: True]
If you test the server ... you will receive an URL not found : 404 error

Philippe.

**Comment by Supportlik** [comment]
Hi, 
I have the same problem and I'm not able to compile plex-media-player.
```
michael@michael-ThinkPad-E520:~/pmp/plex-media-player/build$ conan install ..
PROJECT: Installing /home/michael/pmp/plex-media-player
Requirements
    plexconantool/1.1@plex/public from plex
    web-client-desktop/3.29.7-98ffa9d@plex/public from plex
    web-client-tv/3.13.3-5401c32@plex/public from plex
Packages
    plexconantool/1.1@plex/public:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    web-client-desktop/3.29.7-98ffa9d@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22
    web-client-tv/3.13.3-5401c32@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22

plexconantool/1.1@plex/public: Already installed!
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: Can't find a 'web-client-desktop/3.29.7-98ffa9d@plex/public' package for the specified options and settings:
- Settings: 
- Options: 

ERROR: Missing prebuilt package for 'web-client-desktop/3.29.7-98ffa9d@plex/public'
Try to build it from sources with "--build web-client-desktop"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
building with `conan install .. --build missing` results to a publickey refused exception. Searching in the plex conan repo shows that the web client is available. What should I do?

```
michael@michael-ThinkPad-E520:~/pmp/plex-media-player/build$ conan search -r plex *@*/public
Existing package recipes:

plexconantool/1.0@plex/public
plexconantool/1.1@plex/public
web-client-desktop/2.11.1-b900a6e@plex/public
web-client-desktop/2.12.4-2c8649e@plex/public
web-client-desktop/2.12.4-b545160@plex/public
web-client-desktop/2.12.5-6af0741@plex/public
web-client-desktop/2.12.5-9b613e8@plex/public
web-client-desktop/2.12.5-ac7ff53@plex/public
web-client-desktop/2.12.6-cced9c2@plex/public
web-client-desktop/2.13.0-856ed32@plex/public
web-client-desktop/3.0.0-478e654@plex/public
web-client-desktop/3.0.0-723f887@plex/public
web-client-desktop/3.0.1-75614b9@plex/public
web-client-desktop/3.0.1-dd2abb1@plex/public
web-client-desktop/3.1.1-134e5dd@plex/public
web-client-desktop/3.1.1-dae3dc7@plex/public
web-client-desktop/3.4.0-dcef613@plex/public
web-client-desktop/3.5.0-5fc1e21@plex/public
web-client-desktop/3.5.0-e40051b@plex/public
web-client-desktop/3.6.0-f9302af@plex/public
web-client-desktop/3.7.0-c20c9a2@plex/public
web-client-desktop/3.7.0-d711f4a@plex/public
web-client-desktop/3.9.0-2e66adb@plex/public
web-client-desktop/3.9.1-85417e0@plex/public
web-client-desktop/3.10.0-efd1768@plex/public
web-client-desktop/3.12.0-b3abe11@plex/public
web-client-desktop/3.14.1-762b124@plex/public
web-client-desktop/3.14.1-8530cc0@plex/public
web-client-desktop/3.20.6-b82494d@plex/public
web-client-desktop/3.21.2-8b92636@plex/public
web-client-desktop/3.26.2-3d9c616@plex/public
web-client-desktop/3.26.2-a67b70b@plex/public
web-client-desktop/3.29.7-98ffa9d@plex/public
web-client-tv/2.10.8-3a42321@plex/public
web-client-tv/2.10.8-3c44295@plex/public
web-client-tv/2.10.8-42d3aaa@plex/public
web-client-tv/2.10.8-738db92@plex/public
web-client-tv/2.10.8-7de1963@plex/public
web-client-tv/2.10.8-9a2e1fb@plex/public
web-client-tv/2.10.8-ade70eb@plex/public
web-client-tv/2.10.8-fa2852f@plex/public
web-client-tv/2.10.8-fd540f9@plex/public
web-client-tv/2.12.7-4d3ceb0@plex/public
web-client-tv/2.13.1-93689d3@plex/public
web-client-tv/2.13.1-be42e24@plex/public
web-client-tv/3.0.1-58dd77c@plex/public
web-client-tv/3.1.1-134e5dd@plex/public
web-client-tv/3.1.1-525366a@plex/public
web-client-tv/3.1.1-dae3dc7@plex/public
web-client-tv/3.3.0-70a4215@plex/public
web-client-tv/3.7.0-c20c9a2@plex/public
web-client-tv/3.13.1-bbd9c62@plex/public
web-client-tv/3.13.1-cb96c539@plex/public
web-client-tv/3.13.2-56c55e3@plex/public
web-client-tv/3.13.2-cb96c53@plex/public
web-client-tv/3.13.3-5401c32@plex/public
web-client-tv2/2.12.5-4dc8657f@plex/public
web-client-tv2/3.19.2-cff0356a@plex/public
web-client-tv2/3.24.0-c4fa2535@plex/public
web-client-tv2/3.25.0-5fddd0b7@plex/public
web-client-tv2/3.26.1-676e46a7@plex/public
web-client-tv2/3.28.0-f8b4c1e6@plex/public
web-client-tv2/3.30.0-22f9886a@plex/public
web-client-tv2/3.30.0-28da1eaa@plex/public
web-client-tv2/3.30.0-61fc5c1b@plex/public
web-client-tv2/3.30.0-8a8105ba@plex/public
web-client-tv2/3.30.0-b090aa46@plex/public
web-client-tv2/3.30.0-bcae8a0b@plex/public
```

**Comment by yochananmarqos** [comment]
I just tried building with the new v1.3.12.755-fed6185a release on Manjaro Linux:

```
[yochanan@OPTIMUS-PRIME build]$ conan install ..
PROJECT: Installing /home/yochanan/pmp/plex-media-player
Requirements
    plexconantool/1.1@plex/public from plex
    web-client-desktop/3.29.7-98ffa9d@plex/public from plex
    web-client-tv/3.13.3-5401c32@plex/public from plex
Packages
    plexconantool/1.1@plex/public:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    web-client-desktop/3.29.7-98ffa9d@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22
    web-client-tv/3.13.3-5401c32@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22

plexconantool/1.1@plex/public: Already installed!
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: Can't find a 'web-client-desktop/3.29.7-98ffa9d@plex/public' package for the specified options and settings:
- Settings: 
- Options: 

ERROR: Missing prebuilt package for 'web-client-desktop/3.29.7-98ffa9d@plex/public'
Try to build it from sources with "--build web-client-desktop"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

[yochanan@OPTIMUS-PRIME build]$ conan install .. --build web-client-desktop
PROJECT: Installing /home/yochanan/pmp/plex-media-player
Requirements
    plexconantool/1.1@plex/public from plex
    web-client-desktop/3.29.7-98ffa9d@plex/public from plex
    web-client-tv/3.13.3-5401c32@plex/public from plex
Packages
    plexconantool/1.1@plex/public:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    web-client-desktop/3.29.7-98ffa9d@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22
    web-client-tv/3.13.3-5401c32@plex/public:8bfbac598d4d5f69fa4f705b512d047ee755aa22

plexconantool/1.1@plex/public: Already installed!
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: Forced build from source
web-client-desktop/3.29.7-98ffa9d@plex/public: Building your package in /home/yochanan/.conan/data/web-client-desktop/3.29.7-98ffa9d/plex/public/build/8bfbac598d4d5f69fa4f705b512d047ee755aa22
web-client-desktop/3.29.7-98ffa9d@plex/public: Configuring sources in /home/yochanan/.conan/data/web-client-desktop/3.29.7-98ffa9d/plex/public/source
Cloning into 'plex-web-client'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: Trying to remove dirty source folder
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: This can take a while for big packages
ERROR: web-client-desktop/3.29.7-98ffa9d@plex/public: Error in source() method, line 17
	plexconantool.download(self)
	ConanException: Error 32768 while executing git clone git@github.com:plexinc/plex-web-client
```

**Comment by dmouriss** [comment]
I'm experiencing the same issue. Is there a known workaround or an idea on when this might get fixed?

**Comment by johnskopis** [comment]
I was able to get this working on linux. I'm sure this isn't supported by plex so YMMV... :man_shrugging: 
I guess the web stuff was never open source but it's possible to build the player on linux using the resources from the OSX build, skipping the conan step entirely.
I downloaded the osx zip and extracted to ~/Downloads/pmp. I built like this:
```
wc="~/Downloads/pmp/Plex Media Player.app/Contents/Resources/web-client"
cmake -DCOMPILER_FLAGS="$CFLAGS" -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/usr/share/qt -DCMAKE_INSTALL_PREFIX=/opt/pmp -DCONAN_WEB-CLIENT-TV2_ROOT="$wc" -DCONAN_WEB-CLIENT-DESKTOP_ROOT="$wc" ..
# Also worked with -GNinja
make
make install
```
I had to copy 2 libs into /opt/pmp/bin:
libEGL.so  libGLESv2.so

I had to modify 1 line of source (I have an intel HD6xx):
```
diff --git a/src/player/OpenGLDetect.cpp b/src/player/OpenGLDetect.cpp
index 1ec58ef..2b8c2f7 100644
--- a/src/player/OpenGLDetect.cpp
+++ b/src/player/OpenGLDetect.cpp
@@ -41,7 +41,7 @@ static QString probeHwdecInterop()
   auto mpv = mpv::qt::Handle::FromRawHandle(mpv_create());
   if (!mpv)
     return "";
-  mpv::qt::set_property(mpv, "hwdec-preload", "auto");
+  mpv::qt::set_property(mpv, "hwdec-preload", "vaapi-copy");
   // Actually creating a window is required. There is currently no way to keep
   // this window hidden or invisible.
   mpv::qt::set_property(mpv, "force-window", true);
```

I think using OSX resources to package on linux is OK. The hacks for rpath(?) and opengl detection are less so...maybe someone wants to fix that properly so it's possible to install using our package managers.

Also, just an observation here: plexmediaplayer uses ~60% cpu compared to ~120% using plexweb in chromium :+1:

**Comment by father-mande** [comment]
Hi,

Hum! interesting ...
I try with Ubuntu 14.04 (up to date) Qt 5.9(.3)
but I fall during make with : 
Scanning dependencies of target PlexMediaPlayer
[ 38%] [ 38%] [ 40%] [ 41%] Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/player/OpenGLDetect.cpp.o
Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o
Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/utils/Log.cpp.o
Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/utils/Utils.cpp.o
/root/sources/pmp220/plex-media-player-2.2.1.758-5dad2d62/src/utils/CachedRegexMatcher.cpp: In member function ‘bool CachedRegexMatcher::addMatcher(const QString&, const QVariant&)’:
/root/sources/pmp220/plex-media-player-2.2.1.758-5dad2d62/src/utils/CachedRegexMatcher.cpp:21:92: error: parameter declared ‘auto’
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                            ^
/root/sources/pmp220/plex-media-player-2.2.1.758-5dad2d62/src/utils/CachedRegexMatcher.cpp: In lambda function:
/root/sources/pmp220/plex-media-player-2.2.1.758-5dad2d62/src/utils/CachedRegexMatcher.cpp:23:14: error: ‘mp’ was not declared in this scope
       return mp.first.pattern() == pattern;

Any advice, did you use Qt 5.7 ? and no error due to change (or not) OpenGLDetect.cpp (if I consider to don't have doing typo for the change)

At all , even not working, lot of thanks for you effort ...
Happy New Year.

Philippe.

**Comment by father-mande** [comment]
Hi,

Following previous test ...
Problem come with Ubun14.04 if I use the default gcc g++ (4.8.4) ... auto type seem unsupported ...
make works with 4.9.4

I run test ... for the moment NO change in OpenGLDetect.cpp, no need to move libEGL/GLESv2 ... I already have it in my default search lib path.

I will continue test with various configuration ...

Thanks again johnskopis 

Philippe.

**Comment by father-mande** [comment]
Hi,

following tests ...
... generation with Qt5.7 or 5.9 without problems
... libs are in my lib cache ... so seem not necessary to put in bin folder ... eventually can be added if need using LD_LIBRARY_PATH or with tools like patchelf to add a library search path
... my CPU/GPU Intel Celeron J3900 don't seem to be able to copy video back in RAM
but the option vaapi-copy can be tested without modding the code by providing a mpv.conf with PlexMediaPlayer

I have not yet run all test ... but seems it's on the right way ...

Again : **lot of thanks johnskopis** ... I provide PMP on NAS to I add credit to you and your workaround ... even I hope a solution for conan problem by Plex team A.S.A.P.

Philippe.

**Comment by father-mande** [comment]
Hi,

End ...
All seem to work as expected ...

F.Y.I. vaapi-copy can be set directly in settings (video hardware acceleration) of PMP 2 ... if available ... so nothing to add / patch

Happy New Year
Philippe.

**Comment by Cromefire** [comment]
Also experienced this error on Ubuntu 17.10, maybe it's a problem with the python version? I'm running 3.6 and conan had some problems with that.

**Comment by markus101** [comment]
Apologies for the delay, but we're moving away from conan for web client dependencies, the changes are currently in the `tv2` branch and we're working on getting those changes into `master`.

See: https://github.com/plexinc/plex-media-player/issues/656 for more details
