### ISSUE TITLE
Failing to build on ubuntu 20.10

### ISSUE THREAD

**Issue by sniff122** [plexinc/plex-media-player#1015]
### Test environment

**PMS Version:** 1.19.4.2935
**PMP Version:** v2.58.0.1076-38e019da
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Ubuntu 20.10 - kernel 5.10.0-051000-generic

### Steps to reproduce
1. Using the dependencies and cmake commands from issue #996 (ik thats for 20.04 but as far as i remember the directories and dependencies are the same)
2. run the make to compile PMP

### Current behavior
1. The compile fails with error 1 on `src/CMakeFiles/PlexMediaPlayer.dir/player/CodecsComponent.cpp.o` with error `call of overloaded ‘append(<brace-enclosed initializer list>)’ is ambiguous`. Below is  paste of the full error
```
/home/lewis/Projects/dpmp/src/player/CodecsComponent.cpp:690:49: error: call of overloaded ‘append(<brace-enclosed initializer list>)’ is ambiguous
  690 |   headers.append({"X-Plex-Platform", "Konvergo"});
      |                                                 ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
                 from /home/lewis/Projects/dpmp/src/player/CodecsComponent.h:4,
                 from /home/lewis/Projects/dpmp/src/player/CodecsComponent.cpp:1:
```

### Expected behavior
1. PMP compiles successfully and builds the executables

**Comment by chaotic-dev** [comment]
PR #962 fixes this. I also ran into this issue.

**Comment by sniff122** [comment]
> PR #962 fixes this. I also ran into this issue.
ahh, lets see if it gets merged or not

**Comment by mseeley** [comment]
@sniff122, @chaotic-dev we've landed #962. Please lmk if the issue persists.

**Comment by sniff122** [comment]
> @sniff122, @chaotic-dev we've landed #962. Please lmk if the issue persists.

yeah that PR patched it
